# 指定大环境 指定测试(test)环境
spring:
  profiles:
    active: test

---
# 开发环境
spring:
  profiles: dev
server:
  port: 8080
---
# 测试环境
spring:
  config:
    activate:
      on-profile: test
server:
  port: 8081
---
# 生产环境
spring:
  config:
    activate:
      on-profile: pro
server:
  port: 8082