server:
  port: 8080

# 数据库相关配置
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url:  jdbc:mysql://localhost:3306/mybatis
    #或者使用spring.datasource.druid.xxx进行数据源配置
    #type: com.alibaba.druid.pool.DruidDataSource

# mybatisPlus 日志输出方式
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


