package com.study.mapper;

import com.study.pojo.emp;
import java.util.List;

public interface empMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_emp
     *
     * @mbggenerated Tue Jan 24 15:45:58 CST 2023
     */
    int deleteByPrimaryKey(Integer empId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_emp
     *
     * @mbggenerated Tue Jan 24 15:45:58 CST 2023
     */
    int insert(emp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_emp
     *
     * @mbggenerated Tue Jan 24 15:45:58 CST 2023
     */
    emp selectByPrimaryKey(Integer empId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_emp
     *
     * @mbggenerated Tue Jan 24 15:45:58 CST 2023
     */
    List<emp> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_emp
     *
     * @mbggenerated Tue Jan 24 15:45:58 CST 2023
     */
    int updateByPrimaryKey(emp record);
}