package com.study.mapper;

import com.study.pojo.dept;
import com.study.pojo.deptExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface deptMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dept
     *
     * @mbggenerated Tue Jan 24 14:11:06 CST 2023
     */
    int countByExample(deptExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dept
     *
     * @mbggenerated Tue Jan 24 14:11:06 CST 2023
     */
    int deleteByExample(deptExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dept
     *
     * @mbggenerated Tue Jan 24 14:11:06 CST 2023
     */
    int deleteByPrimaryKey(Integer deptId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dept
     *
     * @mbggenerated Tue Jan 24 14:11:06 CST 2023
     */
    int insert(dept record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dept
     *
     * @mbggenerated Tue Jan 24 14:11:06 CST 2023
     */
    int insertSelective(dept record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dept
     *
     * @mbggenerated Tue Jan 24 14:11:06 CST 2023
     */
    List<dept> selectByExample(deptExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dept
     *
     * @mbggenerated Tue Jan 24 14:11:06 CST 2023
     */
    dept selectByPrimaryKey(Integer deptId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dept
     *
     * @mbggenerated Tue Jan 24 14:11:06 CST 2023
     */
    int updateByExampleSelective(@Param("record") dept record, @Param("example") deptExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dept
     *
     * @mbggenerated Tue Jan 24 14:11:06 CST 2023
     */
    int updateByExample(@Param("record") dept record, @Param("example") deptExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dept
     *
     * @mbggenerated Tue Jan 24 14:11:06 CST 2023
     */
    int updateByPrimaryKeySelective(dept record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dept
     *
     * @mbggenerated Tue Jan 24 14:11:06 CST 2023
     */
    int updateByPrimaryKey(dept record);
}