package com.study.mapper;

import com.study.pojo.emp;
import com.study.pojo.empExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface empMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_emp
     *
     * @mbggenerated Tue Jan 24 14:11:06 CST 2023
     */
    int countByExample(empExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_emp
     *
     * @mbggenerated Tue Jan 24 14:11:06 CST 2023
     */
    int deleteByExample(empExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_emp
     *
     * @mbggenerated Tue Jan 24 14:11:06 CST 2023
     */
    int deleteByPrimaryKey(Integer empId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_emp
     *
     * @mbggenerated Tue Jan 24 14:11:06 CST 2023
     */
    int insert(emp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_emp
     *
     * @mbggenerated Tue Jan 24 14:11:06 CST 2023
     */
    int insertSelective(emp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_emp
     *
     * @mbggenerated Tue Jan 24 14:11:06 CST 2023
     */
    List<emp> selectByExample(empExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_emp
     *
     * @mbggenerated Tue Jan 24 14:11:06 CST 2023
     */
    emp selectByPrimaryKey(Integer empId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_emp
     *
     * @mbggenerated Tue Jan 24 14:11:06 CST 2023
     */
    int updateByExampleSelective(@Param("record") emp record, @Param("example") empExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_emp
     *
     * @mbggenerated Tue Jan 24 14:11:06 CST 2023
     */
    int updateByExample(@Param("record") emp record, @Param("example") empExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_emp
     *
     * @mbggenerated Tue Jan 24 14:11:06 CST 2023
     */
    int updateByPrimaryKeySelective(emp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_emp
     *
     * @mbggenerated Tue Jan 24 14:11:06 CST 2023
     */
    int updateByPrimaryKey(emp record);
}